git:
  diffContextSize: 10
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
promptToReturnFromSubprocess: false
gui:
  showNumstatInFilesView: true
  wrapLinesInStagingView: true
  theme:
    selectedLineBgColor:
      - "#444444"
    selectedRangeBgColor:
      - "#444444"
