command -v bat &>/dev/null || alias bat="batcat"
alias amend="git commit --amend --no-edit"
alias cm="git commit -m"
alias p="git push"
alias unstage='git reset --mixed HEAD~1'
alias c="claude"
alias k='kiro-cli'
alias w='cd ~/workplace'
alias nvconfig='cd ~/.config/nvim'
alias lg='lazygit'
